<?php
/** Liang Lee Wood Theme For ELgg
 * @package LiangLeeFramework 
 * @Subpackage LiangLeeThemeDesigner, LeeThemeWood
 * @author Liang Lee
 * @ide The code is generated by Liang Lee Php IDE
 * @copyright All right reserved Liang Lee 2013.
 * @File activate.php
 */
 
forward(elgg_add_action_tokens_to_url('action/LeeThemeWood/activate'));