<?php
/** Liang Lee Wood Theme For ELgg
 * @package LiangLeeFramework 
 * @Subpackage LiangLeeThemeDesigner, LeeThemeWood
 * @author Liang Lee
 * @ide The code is generated by Liang Lee Php IDE
 * @copyright All right reserved Liang Lee 2013.
 * @File deactivate
 */
$LeeThemeWood = new LiangLeePath;
include_once($LeeThemeWood->classes('LeeThemeWood').'LiangLeeThemeWood.php');

$deactivate = new LeeThemeWood;
if($deactivate->disable()){
system_message('leeplugin:disabled');
} else {
system_message('leeplugin:disabled:error');

}