<?php
/** Liang Lee Wood Theme For ELgg
 * @package LiangLeeFramework 
 * @Subpackage LiangLeeThemeDesigner, LeeThemeWood
 * @author Liang Lee
 * @ide The code is generated by Liang Lee Php IDE
 * @copyright All right reserved Liang Lee 2013.
 * @File start.php
 */
 
elgg_register_event_handler('init', 'system', 'LiangLeeThemeWood');

function LiangLeeThemeWood(){

	$action = new LiangLeePath;
	elgg_register_action('LeeThemeWood/activate', $action->action('LeeThemeWood')."activate.php");

}

