<?php
/** Liang Lee Configure ThemeDesigner
 * @package LiangLeeFramework 
 * @Subpackage LiangLeeThemeDesigner, LeeThemeWood
 * @author Liang Lee
 * @ide The code is generated by Liang Lee Php IDE
 * @copyright All right reserved Liang Lee 2013.
 * @File en.php
 */
$english = array(	
    'leeplugin:disabled' => 'Plugin Disabled',
    'leeplugin:disabled:error' => 'Cannot disable this plguin',
    'leeplugin:configured' => 'Plugin configured',
    'leeplugin:configured:error' => 'Cannot configure this plugin',
 );
					
add_translation("en", $english);
