<?php
/** Liang Lee Wood Theme For ELgg
 * @package LiangLeeFramework 
 * @Subpackage LiangLeeThemeDesigner, LeeThemeWood
 * @author Liang Lee
 * @ide The code is generated by Liang Lee Php IDE
 * @copyright All right reserved Liang Lee 2013.
 * @File LiangLeeThemeWood.php
 */

class LeeThemeWood {

/**
* Construct a main class
* @uses Framework;
*/
public function __construct(){
   $this->LiangLeeThemeDesigner = 'LiangLeeThemeDesigner';
   $this->LiangLeeThemeWood = 'LeeThemeWood';
   $this->LeeThemeWood = elgg_get_plugin_from_id($this->LiangLeeThemeDesigner);
}

/**
* Set Main Settings for LeeThemeWood
* @uses configure;
*/
public function ini(){
   return array(
   'Leethemed_logotop' => 'disable',
   
   'Leethemed_header_bgorimg' => 'image',
   'Leethemed_header_bgimg' => LiangLeeUrl::construct("mod/{$this->LiangLeeThemeWood}/images/{$this->LiangLeeThemeWood}.jpg"),
   'Leethemed_header_height' => '',
   'Leethemed_header_bgcolor' => '',
      
   'Leethemed_body_bgcolor' => '#F8F8F8',
   
   'Leethemed_search_br' => '#ffffff',
   'Leethemed_tbar_bgorcolor' => 'image',
   'Leethemed_background' => LiangLeeUrl::construct("mod/{$this->LiangLeeThemeWood}/images/topbar.jpg"),
   'Leethemed_tbar_height' => '30',
   'Leethemed_tbar_bgcolor' => '',
    );

}
/**
* Configue LeeThemeWood
* @uses configure;
*/
public function configure(){
$configure = $this->ini();
   foreach($configure  as $var => $settings){
       $this->LeeThemeWood->setSetting($var, $settings);
   }
 return true;  
}
/**
* Deactivate LeeThemeLee
* @uses configure;
*/
public function disable(){
$disable = $this->ini();
    foreach($disable  as $var => $settings){
        $this->LeeThemeWood->setSetting($var, '');
   }
 return true;     
}

}