<?php
/** Liang Lee Wood Theme For ELgg
 * @package LiangLeeFramework 
 * @Subpackage LiangLeeThemeDesigner, LeeThemeWood
 * @author Liang Lee
 * @ide The code is generated by Liang Lee Php IDE
 * @copyright All right reserved Liang Lee 2013.
 * @File activate.php
 */
 
$LeeThemeWood = new LiangLeePath;
include_once($LeeThemeWood->classes('LeeThemeWood').'LiangLeeThemeWood.php');

$configure = new LeeThemeWood;

if($configure->configure()){
system_message('leeplugin:configured');
} else {
system_message('leeplugin:configured:error');
}

forward('upgrade.php');